name: Template

permissions:
  actions: write
  contents: write
  pull-requests: write
  id-token: write

on:
  push:
    branches:
      - main

jobs:
  write_to_repo:
    runs-on: ubuntu-latest

    steps:
      - name: echo run id
        shell: bash
        run: echo run attempt ${{ github.run_number }}
      - name: write a file
        shell: bash
        run: |
          touch foo.txt
          date > foo.txt
          git config --global user.name 'christopherjturner'
          git config --global user.email 'christopherjturner@users.noreply.github.com'
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY
          git checkout "${GITHUB_REF:11}"
          git commit -am "Automated report"
          git push        
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OWNER: ${{ github.repository_owner }}
          REPO: ${{ github.event.repository.name }}
          REPOID: ${{ github.repository_id }}
