name: Template

permissions:
  actions: write
  contents: write
  pull-requests: write
  id-token: write

on:
  push:
    branches:
      - main

jobs:
  write_to_repo:
    runs-on: ubuntu-latest

    steps:
      - name: write a file
        shell: bash
        run: |
          curl -L -X PUT -H "Accept: application/vnd.github+json" -H "Authorization: Bearer $GITHUB_TOKEN" -H "X-GitHub-Api-Version: 2022-11-28" https://api.github.com/repos/$OWNER/$REPO/contents/testfile -d '{"message":"my commit message","committer":{"name":"christopherjturner","email":"christopherjturner@gmail.com"},"content":"bXkgbmV3IGZpbGUgY29udGVudHM="}'
          curl -L -X POST -H "Accept: application/vnd.github+json" -H "Authorization: Bearer $GITHUB_TOKEN" -H "X-GitHub-Api-Version: 2022-11-28" https://api.github.com/repos/$OWNER/$REPO/actions/variables/FOO -d '{"name":"FOO", "value":"Test"}'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OWNER: ${{ github.repository_owner }}
          REPO: ${{ github.event.repository.name }}
